from __future__ import annotations

COLUNAS_PLANILHA_SAIDA: tuple[str, ...] = (
    "id",
    "tipo",
    "sku-pai",
    "sku",
    "ativo",
    "usado",
    "destaque",
    "ncm",
    "gtin",
    "mpn",
    "nome",
    "seo-tag-title",
    "seo-tag-description",
    "descricao-completa",
    "url-video-youtube",
    "estoque-gerenciado",
    "estoque-quantidade",
    "estoque-situacao-em-estoque",
    "estoque-situacao-sem-estoque",
    "preco-sob-consulta",
    "preco-custo",
    "preco-cheio",
    "preco-promocional",
    "marca",
    "peso-em-kg",
    "altura-em-cm",
    "largura-em-cm",
    "comprimento-em-cm",
    "categoria-nome-nivel-1",
    "categoria-nome-nivel-2",
    "categoria-nome-nivel-3",
    "categoria-nome-nivel-4",
    "categoria-nome-nivel-5",
    "imagem-1",
    "imagem-2",
    "imagem-3",
    "imagem-4",
    "imagem-5",
    "grade-genero",
    "grade-produto-com-duas-cores",
    "grade-produto-com-uma-cor",
    "grade-tamanho-de-anelalianca",
    "grade-tamanho-de-calca",
    "grade-tamanho-de-camisacamiseta",
    "grade-tamanho-de-capacete",
    "grade-tamanho-de-tenis",
    "grade-tamanho-juvenil-infantil",
    "grade-voltagem",
    "grade-colecao",
    "grade-estampa-infanti",
    "grade-generos",
    "grade-gorro",
    "grade-modelo-body-frases",
    "grade-tamanho-infantil",
)
"""As 54 colunas da planilha de saída, na ordem exata da exportação real da loja
(`docs/regras-planilha-loja-integrada.md` §2). Nunca reordenar, remover ou incluir coluna."""

COLUNAS_PREENCHIDAS_KMILAA: frozenset[str] = frozenset(
    {
        "tipo",
        "sku-pai",
        "sku",
        "ativo",
        "usado",
        "destaque",
        "gtin",
        "nome",
        "seo-tag-title",
        "seo-tag-description",
        "descricao-completa",
        "estoque-gerenciado",
        "estoque-quantidade",
        "estoque-situacao-em-estoque",
        "estoque-situacao-sem-estoque",
        "preco-sob-consulta",
        "preco-custo",
        "preco-cheio",
        "preco-promocional",
        "marca",
        "peso-em-kg",
        "altura-em-cm",
        "largura-em-cm",
        "comprimento-em-cm",
        "categoria-nome-nivel-1",
        "categoria-nome-nivel-2",
        "categoria-nome-nivel-3",
        "categoria-nome-nivel-4",
        "categoria-nome-nivel-5",
        "imagem-1",
        "imagem-2",
        "imagem-3",
        "imagem-4",
        "imagem-5",
        "grade-produto-com-uma-cor",
        "grade-tamanho-infantil",
    }
)
"""Subconjunto de `COLUNAS_PLANILHA_SAIDA` que o sistema efetivamente escreve.

Fora dele: `id` (deixado em branco para a loja atribuir), `ncm`/`mpn`/`url-video-youtube`
(em branco por decisão) e as demais colunas `grade-*` nunca usadas pela Kmilaa (§2, legenda
"—")."""
